apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-media-data-local-pv
  namespace: ns-simpletyzer
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage2
  local:
    path: /home/felingato/clases/ClasesKubernetes/Practices/kb-django/app_data/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - timmygrande
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-static-data-local-pv
  namespace: ns-simpletyzer
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage2
  local:
    path: /home/felingato/clases/ClasesKubernetes/Practices/kb-django/app_data/static
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - timmygrande
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-media-data-local-pvc
  namespace: ns-simpletyzer
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage2
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-static-data-local-pvc
  namespace: ns-simpletyzer
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage2
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ns-simpletyzer
data:
  SECRET_KEY: tachosama-insecure-fjahlfe=&tp4(p(l(yyp4udx*e7dtp@i-^$!7vq$3k8iwe!p5e
  DB_ENGINE: django.db.backends.postgresql_psycopg2
  DB_DEFAULT: tachoapp
  DB_USER: tacho
  DB_PASSWORD: 123tacho
  DB_HOST: teamtcj.com
  DB_PORT: '30007'
  LANGUAGE_CODE: es-co
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacho-app  # Sets Deployment name
  namespace: ns-simpletyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacho-app
  template:
    metadata:
      labels:
        app: tacho-app
    spec:
      containers:
        - name: tacho-app
          image: felingato1992/kclases:tacho-test # Sets Image
          resources:
            limits:
              memory: "1Gi"
              cpu: "800m"
            requests:
              memory: "300Mi"
              cpu: "400m"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /usr/src/app/media
              name: media-files
            - mountPath: /usr/src/app/static
              name: static-files
      volumes:
        - name: media-files
          persistentVolumeClaim:
            claimName: app-media-data-local-pvc
        - name: static-files
          persistentVolumeClaim:
            claimName: app-static-data-local-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: ns-simpletyzer
spec:
  selector:
    app: tacho-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30008
  type: LoadBalancer