version: '3'
services:
  web:
      build: .
      image: felingato1992/kclases:tacho-test
      #image: felingato1992/kclases:tacho-test
      container_name: "tacho_test_container"
      volumes:
        - ./app/:/usr/src/app
      #  - teamtcj_canvastcj_static_data:/usr/src/app/static
      restart: always
      ports:
      - 8000:8000