version: '3'
services:
  web:
      build: .
      image: "tacho_test"
      container_name: "tacho_test_container"
      volumes:
        - ./app/:/usr/src/app
      #  - teamtcj_canvastcj_static_data:/usr/src/app/static
      restart: always
      ports:
      - 8000:8000