kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage2
  namespace: ns-simpletyzer
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-local-pv
  namespace: ns-simpletyzer
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage2
  local:
    path: /home/felingato/clases/ClasesKubernetes/Practices/kb-django/pg_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - timmygrande
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-local-pvc
  namespace: ns-simpletyzer
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage2
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ns-simpletyzer
data:
  POSTGRES_DB: tachoapp
  POSTGRES_USER: tacho
  POSTGRES_PASSWORD: 123tacho
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
  namespace: ns-simpletyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.6-alpine # Sets Image
          resources:
            limits:
              memory: "1Gi"
              cpu: "800m"
            requests:
              memory: "700Mi"
              cpu: "400m"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pg-local-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: ns-simpletyzer
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer