apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - teamtcj.com
      secretName: letsencrypt
  rules:
    - host: teamtcj.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 30008
