apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-app-pv-claim
  namespace: test
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi