apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-test
  namespace: test
spec:
  hard:
    pods: 5
    services.nodeports: 5
    services.loadbalancers: 5
    replicationcontrollers: 5
    resourcequotas: 2
    secrets: 2
    configmaps: 2
    persistentvolumeclaims: 2
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
